version: "3.8"
services:
  dashy:
    container_name: APOD
    build: .
    ports:
      - 8080:8080
    environment:
      - NASA_API_KEY=''
    restart: unless-stopped


  postgresdb:
    image: postgres:13-alpine
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5


  golang:
    build: .
    container_name: api-task
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - "/apod/api-task/Data/:/Data/"
    depends_on:
      postgresdb:
        condition: service_healthy


volumes:
  database:
  dbdata: